#!/bin/bash
xcodebuild -project "Calabash Playground.xcodeproj" -scheme "Calabash Playground-cal" -destination 'platform=iOS Simulator,name=iPad' build
DEVICE_TARGET='iPad - Simulator - iOS 7.1' cucumber
